language: python

services:
  - docker

jobs:
  include:
    - script:
        - docker build -t hannsen/qbittorrent_search_plugins .
        - docker run hannsen/qbittorrent_search_plugins ./tests/ali213.sh
      name: "ali213"
    - script:
        - docker build -t hannsen/qbittorrent_search_plugins .
        - docker run hannsen/qbittorrent_search_plugins ./tests/smallgames.sh
      name: "smallgames"
